/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package uidialog;

import java.awt.Frame;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.sql.Date;
import java.time.format.DateTimeParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.InstruktorLicenca;
import model.Licenca;
import table_model.InstructorLicenceTableModel;
import uicontroller.Controller;
import uiform.InstruktorLicencaForm;

/**
 *
 * @author milan
 */
public class InstruktorLicencaDialog extends javax.swing.JDialog {

    /**
     * Creates new form CreateInstructorLicenceDialog
     */
    private InstruktorLicencaForm parent;
    private InstruktorLicenca il;
    List<InstruktorLicenca> list;
    public InstruktorLicencaDialog(Frame parent, boolean modal, InstruktorLicenca il, List<InstruktorLicenca> list) {
        super(parent, modal);
        initComponents();
        fillComboBox();
        this.parent=(InstruktorLicencaForm) parent;
        this.il=il;
        this.list=list;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxLicence = new javax.swing.JComboBox<>();
        jTextFieldDate = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldDate.setText("gggg-MM-dd");

        jButtonAdd.setText("Dodaj");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabel1.setText("Datum:");

        jLabel2.setText("Licenca:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxLicence, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDate, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAdd)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

        try{
            String datumSticanja = jTextFieldDate.getText();
            DateTimeFormatter formater = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate localDate = LocalDate.parse(datumSticanja, formater);
            Date sqlDate = Date.valueOf(localDate);

            il.setDatumSticanja(sqlDate);
            il.setLicenca((Licenca) jComboBoxLicence.getSelectedItem());
            for(InstruktorLicenca ilm : list){
                if(ilm.getInstruktor().getIdInstruktor()==il.getInstruktor().getIdInstruktor() &&
                    ilm.getLicenca().getIdLicenca()==il.getLicenca().getIdLicenca()){
                    JOptionPane.showMessageDialog(rootPane, "Greška prilikom unošenja licence, već postoji.","Pogrešan unos licence",JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        
            boolean b = Controller.getInstance().kreirajInstruktorLicenca(il);
            if(b){
                JOptionPane.showMessageDialog(rootPane, "Uspešno uneta licenca.","Uspešno unošenje",JOptionPane.INFORMATION_MESSAGE);
                parent.fillTable();
                this.dispose();
            }
        }catch(DateTimeParseException pe){
            JOptionPane.showMessageDialog(rootPane, "Greška prilikom unošenja datuma, loš format.","Pogrešan format datuma",JOptionPane.ERROR_MESSAGE);
            return;
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Greška prilikom dodavanja licence.\n"+ex.getMessage(),"Neuspešno dodavanje",JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButtonAddActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JComboBox<Licenca> jComboBoxLicence;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldDate;
    // End of variables declaration//GEN-END:variables

    private void fillComboBox() {
        try {
            List<Licenca> list = Controller.getInstance().vratiListuSviLicenca();
            for(Licenca l : list){
                jComboBoxLicence.addItem(l);
            }
        } catch (Exception ex) {
            Logger.getLogger(InstruktorLicencaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
}
