/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package uidialog;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import uicontroller.Controller;
import model.NivoSkijanja;
import uiform.NivoSkijanjaForm;

/**
 *
 * @author milan
 */
public class NivoSkijanjaDialog extends javax.swing.JDialog {

    /**
     * Creates new form NivoSkijanjaDialog
     */
    private NivoSkijanja ns;
    private NivoSkijanjaForm parent;
    public NivoSkijanjaDialog(java.awt.Frame parent, boolean modal, NivoSkijanja ns) {
        super(parent, modal);
        initComponents();
        this.ns=ns;
        this.parent=(NivoSkijanjaForm) parent;
        fillFields();
        setSize(300,250);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonChange = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jLabelValidation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalji nivoa skijanja");
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jTextFieldName);
        jTextFieldName.setBounds(150, 30, 100, 20);

        jLabel1.setText("Naziv nivoa:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 30, 80, 20);

        jButtonAdd.setText("Dodaj");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd);
        jButtonAdd.setBounds(100, 75, 100, 25);

        jButtonBack.setText("Nazad");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(100, 160, 100, 25);

        jButtonDelete.setText("Obriši");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete);
        jButtonDelete.setBounds(100, 110, 100, 25);

        jButtonChange.setText("Izmeni");
        jButtonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonChange);
        jButtonChange.setBounds(100, 75, 100, 25);

        jButtonSave.setText("Sačuvaj");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSave);
        jButtonSave.setBounds(100, 75, 100, 25);

        jLabelValidation.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelValidation.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabelValidation);
        jLabelValidation.setBounds(150, 50, 110, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

        try {
            NivoSkijanja ns = new NivoSkijanja();
            boolean valid = true;
            jLabelValidation.setText("");
            if(jTextFieldName.getText().isEmpty()){
                jLabelValidation.setText("Popunite polje.");
                valid=false;
            }
            if(!valid)
                return;
            ns.setNazivNivoa(jTextFieldName.getText());
            boolean b = Controller.getInstance().kreirajNivoSkijanja(ns);
            if(b){
                JOptionPane.showMessageDialog(rootPane, "Uspešno kreiran nivo skijanja.","Uspešno kreiranje",JOptionPane.INFORMATION_MESSAGE);
                parent.fillTable();
                this.dispose();
                return;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Greška prilikom dodavanja nivoa skijanja. \n"+ex.getMessage(),"Neuspešno kreiranje",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        
        int i =JOptionPane.showConfirmDialog(rootPane, "Da li ste sigurni da želite da obrišete nivo skijanja?","Brisanje nivoa skijanja",JOptionPane.YES_NO_OPTION);
        
        if(i == JOptionPane.YES_OPTION){
            try {

                boolean b = Controller.getInstance().obrisiNivoSkijanja(ns);
                if(b){
                    JOptionPane.showMessageDialog(rootPane, "Uspešno obrisan nivo skijanja.","Uspešno brisanje",JOptionPane.INFORMATION_MESSAGE);
                    parent.fillTable();
                    this.dispose();
                    }
            } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Greška prilikom brisanja nivoa skijanja."+ex.getMessage(),"Neuspešno brisanje",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeActionPerformed
        jButtonSave.setVisible(true);
        jButtonChange.setVisible(false);
        jButtonDelete.setVisible(false);
        jTextFieldName.setEnabled(true);
    }//GEN-LAST:event_jButtonChangeActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {
            boolean valid = true;
            jLabelValidation.setText("");
            if(jTextFieldName.getText().equals(ns.getNazivNivoa())){
                valid=false;
                jLabelValidation.setText("Unesite drugi naziv.");
            }
            if(jTextFieldName.getText().isEmpty()){
                valid=false;
                jLabelValidation.setText("Popunite polje.");
            }
            if(!valid)
                return;
            ns.setNazivNivoa(jTextFieldName.getText());
            boolean b = Controller.getInstance().promeniNivoSkijanja(ns);
            if(b){
                JOptionPane.showMessageDialog(rootPane, "Uspešno izmenjen nivo skijanja.","Uspešna izmena nivoa skijanja",JOptionPane.INFORMATION_MESSAGE);
                parent.fillTable();
                this.dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Greška prilikom izmene nivoa skijanja. \n"+ex.getMessage(),"Neuspešna izmena",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonChange;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelValidation;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables

    private void fillFields() {
        if(ns == null){
            jTextFieldName.setText("");
            jButtonAdd.setVisible(true);
            jButtonDelete.setVisible(false);
        }
        else{
            jTextFieldName.setText(ns.getNazivNivoa());
            jButtonAdd.setVisible(false);
            jButtonSave.setVisible(false);
            jTextFieldName.setEnabled(false);
            
        }
    }
}
