/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uiform;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Instruktor;
import uicontroller.Controller;

/**
 *
 * @author milan
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        fillLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jPasswordFieldRepeatPass = new javax.swing.JPasswordField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldSurname = new javax.swing.JTextField();
        jTextFieldContact = new javax.swing.JTextField();
        jTextFieldUser = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setPreferredSize(new java.awt.Dimension(450, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Ime:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(75, 30, 100, 20);

        jLabel2.setText("Povtrdi šifru:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(75, 205, 100, 20);

        jLabel3.setText("Prezime:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(75, 65, 100, 20);

        jLabel4.setText("Kontakt telefon:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(75, 100, 100, 20);

        jLabel5.setText("Korisničko ime:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(75, 135, 100, 20);

        jLabel6.setText("Šifra:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(75, 170, 100, 20);
        getContentPane().add(jPasswordFieldPass);
        jPasswordFieldPass.setBounds(225, 170, 150, 20);
        getContentPane().add(jPasswordFieldRepeatPass);
        jPasswordFieldRepeatPass.setBounds(225, 205, 150, 20);
        getContentPane().add(jTextFieldName);
        jTextFieldName.setBounds(225, 30, 150, 20);

        jTextFieldSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSurnameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSurname);
        jTextFieldSurname.setBounds(225, 65, 150, 20);
        getContentPane().add(jTextFieldContact);
        jTextFieldContact.setBounds(225, 100, 150, 20);
        getContentPane().add(jTextFieldUser);
        jTextFieldUser.setBounds(225, 135, 150, 20);

        jButtonRegister.setText("Registruj se");
        jButtonRegister.setHideActionText(true);
        jButtonRegister.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister);
        jButtonRegister.setBounds(150, 245, 150, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(225, 50, 150, 15);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(225, 85, 150, 15);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(225, 120, 150, 15);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(225, 155, 200, 15);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(225, 190, 200, 15);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(225, 225, 200, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        try {        
        String pass = String.valueOf(jPasswordFieldPass.getText());
        String repeatPass = String.valueOf(jPasswordFieldRepeatPass.getText());
        String user = jTextFieldUser.getText();
        String name = jTextFieldName.getText();
        String contact = jTextFieldContact.getText();
        String surname = jTextFieldSurname.getText();
        fillLabels();
        boolean valid = true;
        
        if (name.isEmpty()) {
            jLabel7.setVisible(true);
            valid=false;
        }   
        if (surname.isEmpty()) {
            jLabel8.setVisible(true);
            valid=false;
        }
        if (contact.isEmpty()) {
            jLabel9.setVisible(true);
            valid=false;
        }else if (!contact.matches("\\+?[0-9]{9,15}")) {
            jLabel9.setText("Kontakt mora imati 9-15 cifara!");
            jLabel9.setVisible(true);
            valid = false;
        }
        if (user.isEmpty()) {
            jLabel10.setVisible(true);
            valid=false;
        }else if (user.length() < 5) {
            jLabel10.setText("Korisničko ime mora imati bar 5 karaktera!");
            jLabel10.setVisible(true);
            valid = false;
        }
        if (pass.isEmpty()) {
            jLabel11.setVisible(true);
            valid=false;
        }else if (pass.length() < 5) {
            jLabel11.setText("Šifra mora imati bar 5 karaktera!");
            jLabel11.setVisible(true);
            valid = false;
        } else if (!pass.matches(".*\\d.*")) { 
            jLabel11.setText("Šifra mora sadržati bar jedan broj!");
            jLabel11.setVisible(true);
            valid = false;
        }
        if (repeatPass.isEmpty()) {
            jLabel12.setVisible(true);
            valid=false;
        }else if (!pass.equals(repeatPass)) {
            jLabel11.setText("Šifre se ne poklapaju!");
            jLabel12.setText("Šifre se ne poklapaju!");
            jLabel11.setVisible(true);
            jLabel12.setVisible(true);
            valid = false;
        }   
    
        
        if(!valid){
            
            return;
        }
        Instruktor i = new Instruktor(0, name, surname, contact, user, pass);
        i = Controller.getInstance().kreirajInstruktor(i);
        JOptionPane.showMessageDialog(this, i.getKorisnickoIme()+" se registrovao/la!", "Register", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška prilikom registrovanja. \n"+ex.getMessage(), "Register", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jTextFieldSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSurnameActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JPasswordField jPasswordFieldRepeatPass;
    private javax.swing.JTextField jTextFieldContact;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSurname;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables

    private void fillLabels() {
        jLabel7.setText("Unesite ime!"); 
        jLabel8.setText("Unesite prezime!"); 
        jLabel9.setText("Unesite kontakt telefon!"); 
        jLabel10.setText("Unesite korisničko ime!"); 
        jLabel11.setText("Unesite šifru!"); 
        jLabel12.setText("Ponovite šifru!"); 
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
    }
}
