/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uiform;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Instruktor;
import uicontroller.Controller;

/**
 *
 * @author milan
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jPasswordFieldRepeatPass = new javax.swing.JPasswordField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldSurname = new javax.swing.JTextField();
        jTextFieldContact = new javax.swing.JTextField();
        jTextFieldUser = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Ime:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(75, 30, 100, 20);

        jLabel2.setText("Povtrdi šifru:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(75, 180, 100, 20);

        jLabel3.setText("Prezime:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(75, 60, 100, 20);

        jLabel4.setText("Kontakt telefon:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(75, 90, 100, 20);

        jLabel5.setText("Korisničko ime:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(75, 120, 100, 20);

        jLabel6.setText("Šifra:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(75, 150, 100, 20);
        getContentPane().add(jPasswordFieldPass);
        jPasswordFieldPass.setBounds(225, 150, 150, 20);
        getContentPane().add(jPasswordFieldRepeatPass);
        jPasswordFieldRepeatPass.setBounds(225, 180, 150, 20);
        getContentPane().add(jTextFieldName);
        jTextFieldName.setBounds(225, 30, 150, 20);

        jTextFieldSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSurnameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSurname);
        jTextFieldSurname.setBounds(225, 60, 150, 20);
        getContentPane().add(jTextFieldContact);
        jTextFieldContact.setBounds(225, 90, 150, 20);
        getContentPane().add(jTextFieldUser);
        jTextFieldUser.setBounds(225, 120, 150, 20);

        jButtonRegister.setText("Registruj se");
        jButtonRegister.setHideActionText(true);
        jButtonRegister.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister);
        jButtonRegister.setBounds(150, 245, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        try {        
        String pass = String.valueOf(jPasswordFieldPass.getText());
        String repeatPass = String.valueOf(jPasswordFieldRepeatPass.getText());
        String user = jTextFieldUser.getText();
        String name = jTextFieldName.getText();
        String contact = jTextFieldContact.getText();
        String surname = jTextFieldSurname.getText();
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(this, "Unesite ime!","Register",JOptionPane.ERROR_MESSAGE);
            return;
        }else if(surname.isEmpty()){
            JOptionPane.showMessageDialog(this, "Unesite prezime!","Register",JOptionPane.ERROR_MESSAGE);
            return;
        }else if(user.isEmpty()){
            JOptionPane.showMessageDialog(this, "Unesite korisničko ime!","Register",JOptionPane.ERROR_MESSAGE);
            return;
        }else if(contact.isEmpty()){
            JOptionPane.showMessageDialog(this, "Unesite kontakt broj!","Register",JOptionPane.ERROR_MESSAGE);
            return;
        }else if(pass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Unesite šifru!","Register",JOptionPane.ERROR_MESSAGE);
            return;
        }else if(repeatPass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ponovite šifru!","Register",JOptionPane.ERROR_MESSAGE);
            return;
        }else if(!pass.equals(repeatPass)){
            JOptionPane.showMessageDialog(this, "Šifre se ne poklapaju!","Register",JOptionPane.ERROR_MESSAGE);
            return;
        }
            
        
        
        Instruktor i = new Instruktor(0, name, surname, contact, user, pass);
        i = Controller.getInstance().register(i);
        JOptionPane.showMessageDialog(this, i.getKorisnickoIme()+" se registrovao/la!", "Register", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška prilikom registrovanja. \n"+ex.getMessage(), "Register", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jTextFieldSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSurnameActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JPasswordField jPasswordFieldRepeatPass;
    private javax.swing.JTextField jTextFieldContact;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSurname;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
